version: 2
jobs:
  build:
    docker:
      - image: theorangeone/docker-pandoc
    steps:
      - checkout:
          name: Checkout project source
      - run:
          name: Build document
          command: make
      - store_artifacts:
          name: Store built PDF
          path: privacy.pdf
          destination: privacy.pdf
